
### 应用配置
application:
  host: 0.0.0.0
  mode: dev
  port: "8001"
  version: 1.0.2
  is-sync: 0
  writertimeout: 2
  readTimeout: 1
### 数据库配置
database:
  dbtype: mysql
  host: 192.168.1.1
  name: opencodes.top
  password:
  port: 3306
  username: root
## 日志配置
log:
  dir: config/seelog.xml
  level: debug
  format: json
  log-in-console: false

## redis 配置
redis:
  addr: 192.168.1.1:6381
  db: 0
  password: ""

## 上传配置
upload:
  dir: upload

## jwt 配置
jwt:
 secret: opencodes
 timeout: 3600
